services:
  ip-update:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-5555}:${PORT:-5555}"
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${PORT:-5555}/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - ./logs:/app/logs